### ISSUE TITLE
Add a CONTRIBUTORS.MD to this repository 

### ISSUE THREAD

**Issue by tanmaymohan** [tanmaymohan/FunnyDiscordBot#3]
Contribute to this project and also add a .MD file with your name.

**Comment by Danny-UKDM** [comment]
I'll take it

**Comment by Danny-UKDM** [comment]
#5 PR for start of CONTRIBUTORS.MD
#4 PR for a good contribution guidelines .md

**Comment by tanmaymohan** [comment]
Nice work 👍
